/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SurfacesRouteImport } from './routes/surfaces'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SchemasRouteImport } from './routes/schemas'
import { Route as HealthRouteImport } from './routes/health'
import { Route as GapsRouteImport } from './routes/gaps'
import { Route as EndpointsRouteImport } from './routes/endpoints'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubnetsIndexRouteImport } from './routes/subnets.index'
import { Route as ProvidersIndexRouteImport } from './routes/providers.index'
import { Route as SubnetsNetuidRouteImport } from './routes/subnets.$netuid'
import { Route as ProvidersSlugRouteImport } from './routes/providers.$slug'

const SurfacesRoute = SurfacesRouteImport.update({
  id: '/surfaces',
  path: '/surfaces',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemasRoute = SchemasRouteImport.update({
  id: '/schemas',
  path: '/schemas',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const GapsRoute = GapsRouteImport.update({
  id: '/gaps',
  path: '/gaps',
  getParentRoute: () => rootRouteImport,
} as any)
const EndpointsRoute = EndpointsRouteImport.update({
  id: '/endpoints',
  path: '/endpoints',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubnetsIndexRoute = SubnetsIndexRouteImport.update({
  id: '/subnets/',
  path: '/subnets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIndexRoute = ProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubnetsNetuidRoute = SubnetsNetuidRouteImport.update({
  id: '/subnets/$netuid',
  path: '/subnets/$netuid',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersSlugRoute = ProvidersSlugRouteImport.update({
  id: '/providers/$slug',
  path: '/providers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/endpoints': typeof EndpointsRoute
  '/gaps': typeof GapsRoute
  '/health': typeof HealthRoute
  '/schemas': typeof SchemasRoute
  '/status': typeof StatusRoute
  '/surfaces': typeof SurfacesRoute
  '/providers/$slug': typeof ProvidersSlugRoute
  '/subnets/$netuid': typeof SubnetsNetuidRoute
  '/providers/': typeof ProvidersIndexRoute
  '/subnets/': typeof SubnetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/endpoints': typeof EndpointsRoute
  '/gaps': typeof GapsRoute
  '/health': typeof HealthRoute
  '/schemas': typeof SchemasRoute
  '/status': typeof StatusRoute
  '/surfaces': typeof SurfacesRoute
  '/providers/$slug': typeof ProvidersSlugRoute
  '/subnets/$netuid': typeof SubnetsNetuidRoute
  '/providers': typeof ProvidersIndexRoute
  '/subnets': typeof SubnetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/endpoints': typeof EndpointsRoute
  '/gaps': typeof GapsRoute
  '/health': typeof HealthRoute
  '/schemas': typeof SchemasRoute
  '/status': typeof StatusRoute
  '/surfaces': typeof SurfacesRoute
  '/providers/$slug': typeof ProvidersSlugRoute
  '/subnets/$netuid': typeof SubnetsNetuidRoute
  '/providers/': typeof ProvidersIndexRoute
  '/subnets/': typeof SubnetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/endpoints'
    | '/gaps'
    | '/health'
    | '/schemas'
    | '/status'
    | '/surfaces'
    | '/providers/$slug'
    | '/subnets/$netuid'
    | '/providers/'
    | '/subnets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/endpoints'
    | '/gaps'
    | '/health'
    | '/schemas'
    | '/status'
    | '/surfaces'
    | '/providers/$slug'
    | '/subnets/$netuid'
    | '/providers'
    | '/subnets'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/endpoints'
    | '/gaps'
    | '/health'
    | '/schemas'
    | '/status'
    | '/surfaces'
    | '/providers/$slug'
    | '/subnets/$netuid'
    | '/providers/'
    | '/subnets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EndpointsRoute: typeof EndpointsRoute
  GapsRoute: typeof GapsRoute
  HealthRoute: typeof HealthRoute
  SchemasRoute: typeof SchemasRoute
  StatusRoute: typeof StatusRoute
  SurfacesRoute: typeof SurfacesRoute
  ProvidersSlugRoute: typeof ProvidersSlugRoute
  SubnetsNetuidRoute: typeof SubnetsNetuidRoute
  ProvidersIndexRoute: typeof ProvidersIndexRoute
  SubnetsIndexRoute: typeof SubnetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/surfaces': {
      id: '/surfaces'
      path: '/surfaces'
      fullPath: '/surfaces'
      preLoaderRoute: typeof SurfacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemas': {
      id: '/schemas'
      path: '/schemas'
      fullPath: '/schemas'
      preLoaderRoute: typeof SchemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaps': {
      id: '/gaps'
      path: '/gaps'
      fullPath: '/gaps'
      preLoaderRoute: typeof GapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endpoints': {
      id: '/endpoints'
      path: '/endpoints'
      fullPath: '/endpoints'
      preLoaderRoute: typeof EndpointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subnets/': {
      id: '/subnets/'
      path: '/subnets'
      fullPath: '/subnets/'
      preLoaderRoute: typeof SubnetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/': {
      id: '/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof ProvidersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subnets/$netuid': {
      id: '/subnets/$netuid'
      path: '/subnets/$netuid'
      fullPath: '/subnets/$netuid'
      preLoaderRoute: typeof SubnetsNetuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$slug': {
      id: '/providers/$slug'
      path: '/providers/$slug'
      fullPath: '/providers/$slug'
      preLoaderRoute: typeof ProvidersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EndpointsRoute: EndpointsRoute,
  GapsRoute: GapsRoute,
  HealthRoute: HealthRoute,
  SchemasRoute: SchemasRoute,
  StatusRoute: StatusRoute,
  SurfacesRoute: SurfacesRoute,
  ProvidersSlugRoute: ProvidersSlugRoute,
  SubnetsNetuidRoute: SubnetsNetuidRoute,
  ProvidersIndexRoute: ProvidersIndexRoute,
  SubnetsIndexRoute: SubnetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
